import java.util.HashMap;

public class Hashmatique {
    public static void main(String[] args){
        HashMap<String, String> trackList = new HashMap<String, String>();
        trackList.put("Rock Salt And Nails", "By the banks of the river. Where the willows hang down. The wild birds they warble. With a low moanin' sound./Way down in the hollow. Where the river runs cold. It was there I first listened. To the lies that you told./ Now I lie on my back. And I see your sweet face. The past I remember. Time can't erase./ And the letters you wrote me. They were written in shame. And I know that your conscience.. Still echoes my name./ Now if the ladies were blackbirds. If the ladies were thrushes. Well I'd lie there for hours. In the chilly cold marshes./ And if the women were squirrels. With them high bushy tails. Well I'd load up my shotgun. With rock salt and nails./ I'd load up my shotgun. With rock salt and nails.");
        trackList.put("Lady May","I'm a stone's throw from the mill.And I'm a good walk to the river.When my workin' day is over.We'll go swim our cares away.Put your toes down in the water.And a smile across your face.And tell me that you love me.Lovely Lady May./ Now I ain't the sharpest chisel. That your hands have ever held. But darlin' I could love you well. Til' the roll is called on high. I've seen my share of trouble. And I've held my weight in shame. But I'm baptized in your name. Lovely Lady May./ Lord the wind can leave you shiverin'. As it waltzes o'er the leaves. It's been rushin' through my timber. Til' your love brought on the spring. Now the mountains all are blushin'. And they don't know what to say. 'Cept a good long line of praises. For my lovely Lady May./ Now I ain't the toughest hickory. That your ax has ever felled. But I'm a hickory just as well. I'm a hickory all the same. I came crashin' through the forest. As you cut my roots away. And I fell a good long ways. For my lovely Lady May.");
        trackList.put("Universal Sound","Up in Pocahontas in the Cranberry Glades. Ain't got bars, nor the charge to call her anyways. My mind's a mile a minute. And my thoughts they bark like hounds. I focus on my breathing and the universal sound./ I think about my darlin' girl sleepin' all alone. I pray the stars will shoot her all the wishes she can hold. On the day that I return I aim to lay her down. But right now I am focused on the universal sound./ I think about tobacco juice and mason jars of shine.I think about the vices I've let take me over time.I recall when I's a baby, I didn't need nothin' around.But a little bitty rattler and the universal sound./ I'd close my eyes.It was all so clear.It was all right then.It was all right here./ I focus on my breathin' and the universal sound.I let it take me over from the toenails to the crown.Of the body that I'm in till they put me in the ground.And I return to the chorus of the universal sound./ I've been up on the mountain.And I've seen his wondrous grace.I've sat there on a barstool and I've looked him in the face.He seemed a little haggard, but it did not slow him down.He was hummin' to the neon of the universal sound.");
        trackList.put("Whitehouse Road", "Early in the morning when the sun does rise. Layin' in the bed with bloodshot eyes. Late in the evenin' when the sun sinks low. Well that's about time my rooster crows. I got women up and down this creek. And they keep me going and my engine clean. Run me ragged but I don't fret. Cause there ain't been one slow me down none yet./ Get me drinking' that moonshine. Get me higher than the grocery bill. Take my troubles to the highwall. Throw 'em in the river and get your fill. We been sniffing that cocaine. Ain't nothin' better when the wind cuts cold. Lord it's a mighty hard livin'. But a damn good feelin' to run these roads./ I got people try to tell me, Red. Keep this livin' and you'll wind up dead. Cast your troubles on the Lord of Lord's. Or wind up laying on a coolin' board. But I got buddies up White House Road. And they keep me strutting when my feet hang low. Rotgut whiskey gonna ease my pain. 'N all this runnin's gonna keep me sane./ Get me drinking' that moonshine. Get me higher than the grocery bill. Take my troubles to the highwall. Throw 'em in the river and get your fill. We been sniffing that cocaine. Ain't nothin' better when the wind cuts cold. Lord it's a mighty hard livin'. But a damn good feelin' to run these road It's a damn good feelin' to run these roads./ When they lay me in the cold hard clay. Won't ya sing them hymns while the banjo plays. You can tell them ladies that they ought not frown. Cause there ain't been nothing ever held me down. Lawmen, women or a shallow grave. Same ol' blues just a different day./ Get me drinking' that moonshine. Get me higher than the grocery bill. Take my troubles to the highwall. Throw 'em in the river and get your fill. We been sniffing that cocaine. Ain't nothin' better when the wind cuts cold. Lord it's a mighty hard livin'. But a damn good feelin' to run these roads. It's a damn good feelin' to run these roads. It's a damn good feelin' to run these roads.");
        System.out.println(trackList.get("Lady May"));

        for(HashMap.Entry<String,String> titleLyrics : trackList.entrySet()){
            System.out.println("Key: "+titleLyrics.getKey()+", Value: "+titleLyrics.getValue());
        }
    }
}